### ISSUE TITLE
Error when trying to install cfn-model (via cfn-nag) on Windows Git Bash

### ISSUE THREAD

**Issue by Aweponken** [stelligent/cfn-model#2]
Using a fresh Git Bash and Ruby 2.4.1p111 I can't install cfn-nag because the installation of cfn-model fails with the following message:
`ERROR:  While executing gem ... (Errno::EINVAL)
    Invalid argument @ rb_sysopen - C:/Ruby24/lib/ruby/gems/2.4.0/gems/cfn-model-0.0.6/lib/cfn-model/schema/AWS::CloudFront::Distribution.yml
`
The schema folder is empty and when I try to copy the files there, it just deletes them during the next installation.

**Comment by erickascic** [comment]
Hmm.... the colon in the filename is probably giving Windows a coronary.  I can probably work out an alternate character to substitute

**Comment by erickascic** [comment]
cfn-nag 0.1.7 and cfn-model 0.0.8 should install on Windoze now.  Beware I'm doing my dev on Mac and Linux... I welcome any fixes to make things play nice on Windoze but I'm definitely not testing on Windoze regularly

**Comment by Aweponken** [comment]
Works like a charm, thanks!
