### ISSUE TITLE
Support for "Parameters" in cfn_model

### ISSUE THREAD

**Issue by xysr89** [stelligent/cfn-model#28]
Hi!

I am working on https://github.com/stelligent/cfn_nag/issues/49 which I think this feature may be useful for us. 

Did some research and looks like inside `cfn_model.rb` we only have `resources` available which the resources are loaded by the parser, and if we would like to access anything else(eg. metadata and parameters) we need to use `raw_model` to get it. 

Since a big perspective of `cfn_nag` is security and credentials are commonly loaded into the cfn templates via parameters so i think it would be beneficial to have this feature implemented :smile:

**Comment by bjsemrad** [comment]
This is something my team has been considering as well. I will probably be working on it as a feature and submit a pull request for in the next few weeks, I'll keep you posted.

**Comment by erickascic** [comment]
I'll have Parameters support in the model by end of today.  I think I've got something useful that's ready for helping with the NoEcho based rule but.... looking into also providing a way to reference external parameter values so that rules can do something like flag an ingress cidr of 0.0.0.0/0 that is parameterized

**Comment by erickascic** [comment]
Ok, I think 0.1.20 addresses this.  I took a stab at writing the rule for NoEcho=true for an RDS::Instance in cfn-nag to make sure there were no surprises..... the one rub is that if somebody specifies a JSON values file for a NoEcho parameter, the actual value will be resolved which is not want you want when you are trying to test the actual reference..... I'm going to wave my hands on this and say you shouldn't be specifying values for NoEcho parameters.
