### ISSUE TITLE
Wildcard Rules Too Permissive

### ISSUE THREAD

**Issue by ialford** [stelligent/cfn-model#37]
The models for wildcards, such as in the [Statement Model](https://github.com/stelligent/cfn-model/blob/master/lib/cfn-model/model/statement.rb), are too broad. This ends up impacting [cfn-nag](https://github.com/stelligent/cfn_nag) users by identifying warnings on resources that are considerably scoped down yet still have an asterisk - such as `"arn:${AWS::Partition}:s3:::${S3Bucket}/*"` on an `s3:GetObject` policy, that could be intentional. 

I would like to see this check scoped down if possible - I know this is a considerable challenge since ARN conventions differ from service to service.

**Comment by erickascic** [comment]
Agreed - there are definitely some asterisks where it depends.

**Comment by erickascic** [comment]
@ialford after much delay, going to work on this now.  i'm going to add some warnings for partial wildcards, and update the failing violations to only fail when its full up "*".  there are cases where you must use "*" (like service catalog/s3) but in that case a resource suppression should do the trick
