### ISSUE TITLE
Exception when parsing Serverless::Function with implicit code

### ISSUE THREAD

**Issue by erickascic** [stelligent/cfn-model#48]
Apparently legal (despite the Function specification?) to have neither CodeUri nor InlineCode and look for the handler in (js) file in same directory as template.

cfn-model should transform this function into a Lambda function with no code... basically just don't throw an exception

**Comment by pshelby** [comment]
@erickascic Looks like this is working properly.  Might be safe to close this issue.

https://github.com/stelligent/cfn-model/blob/83f4337c1a99105b5e16ab6f9b46bb655258bd31/spec/transforms/serverless_spec.rb#L110-L120

```
$ date
Wed Feb 12 08:59:01 EST 2020
$ git pull upstream master
From https://github.com/stelligent/cfn-model
 * branch            master     -> FETCH_HEAD
Already up to date.
$ bundle exec rspec spec/transforms/serverless_spec.rb
........

Finished in 0.01718 seconds (files took 0.14363 seconds to load)
8 examples, 0 failures

Coverage report generated for RSpec to cfn-model/coverage. 638 / 972 LOC (65.64%) covered.
$
```
