### ISSUE TITLE
Investigate better support for transforms

### ISSUE THREAD

**Issue by erickascic** [stelligent/cfn-model#68]
Investigate a "mode" for parsing that attempts to invoke a transform Lambda.... and then turn the model into what comes back.  A few things to consider:

1. Needs to be a mode so that it can be turned off and we stick to "real" offline static analysis
2. The offline mode needs to safely ignore transforms (and it doesn't now).  For example, if Resources is missing without a transform, still fail.  If there is a transform.... warn that it's missing instead of blowing up?
3. Need to consider managing permissions to invoke the transform and the region and all that junk.
4. As far as line numbers and all that goes.... not sure how that would work since the original template and the "emitted" model are quite different.  Perhaps emit that version of the template and reference line numbers against that?

**Comment by pshelby** [comment]
I began investigating performing these transforms using either native logic (`aws-sam-translator` Python module for SAM templates) or creating the associated Lambda functions for custom transforms, however there are several impediments to executing this functionality.

* The ruby cfn-model code would need to call Python code, which would either require a Python environment in which to call the code or for the Python code to be compiled for the specific architecture where cfn-model was running.
* cfn-model would need AWS credentials to spin up the custom transform Lambda function in an account and invoke it, or again would need a Python environment in which to locally invoke the SAM CLI tools.

At this point in the cfn_nag/cfn-model lifecycle, I believe we need to focus on other pain points.
