### ISSUE TITLE
Template functions in resource names fail validation

### ISSUE THREAD

**Issue by otakusid** [stelligent/cfn-model#8]
Hi, I try to parse template that use [CloudFormation Intrinsic Functions](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference.html) to generate resource names and it brings to parsing error:

> `pre_validate_model': Basic CloudFormation syntax error:[#<Kwalify::ValidationError: [/Resources/ECSTaskRolePolicies/Properties/PolicyName] not a string.>, #<Kwalify::ValidationError: [/Resources/ECSServiceRolePolicy/Properties/PolicyName] not a string.>] (ParserError)

Here is resource sample that fail parser:

```json
"ECSTaskRolePolicies": {
  "Type": "AWS::IAM::Policy",

  "Properties": {
    "PolicyName" : { "Fn::Sub" : "${EnvPrefix}-my-policy-${EnvSuffix}" },
    "Roles" : [ { "Ref": "ECSTaskRole" } ],

    "PolicyDocument" : {
      "Version" : "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Action": [
            "logs:CreateLogGroup",
            "logs:CreateLogStream",
            "logs:PutLogEvents"
          ],

          "Resource": "arn:aws:logs:*:*:*"
        }
      ]
    }
  }
}
```

**Comment by erickascic** [comment]
Yep, that's a bug.  The schema for that field should be "any" instead of "str".  Pushing fix shortly.

**Comment by otakusid** [comment]
Cool, thanks!

**Comment by erickascic** [comment]
0.1.3 has the fix

**Comment by otakusid** [comment]
confirm, `AWS::IAM::Policy` now accept functions in the `PolicyName` property
